env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'
  config: 'RelWithDebInfo'

name: CMake Build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '23 1 * * 0'
  release:
    types: [published]

defaults:
  run:
    shell: bash

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: kreczko/xrootd-hdfs-build:latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          scl enable devtoolset-8 "cmake3 -B ${{ env.build }} -DCMAKE_BUILD_TYPE=${{ env.config }}"

      - name: Build xrootd-hdfs
        run: |
          scl enable devtoolset-8 "make -C ${{ env.build }}"
